function(felogram_configure_api)
    set(FELOGRAM_API_MODE "Account" CACHE STRING "Account or Baseline API configuration.")
    set_property(CACHE FELOGRAM_API_MODE PROPERTY STRINGS Account Baseline)
    set(FELOGRAM_API_CONFIG "${CMAKE_SOURCE_DIR}/.local/telegram-api.local.json" CACHE FILEPATH "Private maintainer API configuration.")
    option(FELOGRAM_DISTRIBUTION "Require maintainer-owned API configuration for packaging." OFF)
    if (NOT FELOGRAM_API_MODE MATCHES "^(Account|Baseline)$")
        message(FATAL_ERROR "Felogram API mode must be Account or Baseline.")
    endif()
    if (FELOGRAM_API_MODE STREQUAL "Baseline")
        if (FELOGRAM_DISTRIBUTION)
            message(FATAL_ERROR "Baseline API configuration cannot be distributed.")
        endif()
        set(felogram_api_id 17349)
        set(felogram_api_hash 344583e45741c457fe1862106095a5eb)
        set(felogram_api_baseline true)
    else()
        if (NOT EXISTS "${FELOGRAM_API_CONFIG}")
            message(FATAL_ERROR "Felogram account setup required: create .local/telegram-api.local.json with your own api_id and api_hash. See docs/REAL_ACCOUNT_TESTING.md. No baseline fallback is enabled.")
        endif()
        file(READ "${FELOGRAM_API_CONFIG}" felogram_api_json)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${FELOGRAM_API_CONFIG}")
        string(JSON felogram_api_id ERROR_VARIABLE id_error GET "${felogram_api_json}" api_id)
        string(JSON felogram_api_hash ERROR_VARIABLE hash_error GET "${felogram_api_json}" api_hash)
        if (id_error OR hash_error)
            message(FATAL_ERROR "Private API configuration must be JSON with api_id and api_hash fields. Values were not logged.")
        endif()
        string(LENGTH "${felogram_api_hash}" hash_length)
        string(TOLOWER "${felogram_api_hash}" felogram_api_hash)
        if (NOT felogram_api_id MATCHES "^[1-9][0-9]*$" OR felogram_api_id GREATER 2147483647
            OR NOT hash_length EQUAL 32 OR NOT felogram_api_hash MATCHES "^[0-9a-fA-F]+$")
            message(FATAL_ERROR "Private API configuration requires a positive 32-bit api_id and a 32-character hexadecimal api_hash. Values were not logged.")
        endif()
        if (felogram_api_id EQUAL 17349 OR felogram_api_hash STREQUAL "344583e45741c457fe1862106095a5eb")
            message(FATAL_ERROR "Account builds require maintainer-owned API configuration, not the upstream sample.")
        endif()
        set(felogram_api_baseline false)
    endif()
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/felogram")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../SourceFiles/core/felogram_api_config.h.in"
        "${CMAKE_BINARY_DIR}/felogram/felogram_api_config.h" @ONLY)
    message(STATUS "Felogram API mode: ${FELOGRAM_API_MODE}; private values are not logged.")
endfunction()
